### ISSUE TITLE
Labels for PadChest Zero-shot Classification

### ISSUE THREAD

**Issue by SinuoWang** [SUSTechBruce/Med-UniC#4]
Hi,

In **zero-shot_pdc.py** I saw you have 10 disease labels : 

 cxr_labels: List[str] = ['Atelectasis','Cardiomegaly', 
                                          'Consolidation', 'Edema','Pleural Effusion', 'Hilar Enlargement', 'Pneumothorax', 'Pneumonia', 'Vascular Redistribution', 'Heart Insufficiency']

However, in the padchest csv file, there are around 190 unique labels (physician labelled). I am confused about what labels should be used, and hope I can get some clarifications. Cheers!

**Comment by SinuoWang** [comment]
Hi! I just saw **preprocess_pdc.py**. You categorized all the fine-grained finding labels into 12 big disease classes by checking the string, right?

**Comment by SUSTechBruce** [comment]
Yep, that's it.
