### ISSUE TITLE
Fine-tuning task parameter settings

### ISSUE THREAD

**Issue by zoule41** [SUSTechBruce/Med-UniC#8]
I am curious why in the code for downstream fine-tuning tasks (mgca_vit_finetuner.py), when the dataset is Covid, the number of categories is set to 2? Shouldn't it be classified into three categories?
<img width="595" alt="image" src="https://github.com/SUSTechBruce/Med-UniC/assets/95894798/664e52b1-afb9-4618-af4f-1ca5d15e9e3b">

**Comment by cheliu-computation** [comment]
Hi, thanks for your interest on our work.
In the current version of COVIDx, the categories are two, rather than three.
